version: "3.7"

services:
    api:
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        volumes:
            - ~/.gitconfig:/root/.gitconfig
            - ..:/workspace
        command: sleep infinity

    db:
        image: postgres:12.3
        restart: always
        ports: 
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: postgres

